<a href="https://colab.research.google.com/github/Mtigno14/Linear-Algebra-58019/blob/main/Determinant_of_Matrix.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
import numpy as np
A = np.array([[1, 2, -1],[4, 6, -2],[-1, 3, 3]]) #the given 3x3 matrix
print(A)
print("\nThe answer is: ")
print(np.linalg.det(A))
print("\nor equal to")
print(round(np.linalg.det(A)))

[[ 1  2 -1]
 [ 4  6 -2]
 [-1  3  3]]

The answer is: 
-13.999999999999996

or equal to
-14
