<a href="https://colab.research.google.com/github/Mtigno14/Linear-Algebra-58019/blob/main/Eigenvalue_and_Eigenvector.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [27]:
import numpy as np
from scipy.linalg import solve

A = np.array([[-12,3],[4,1]]) #matrix A
print("Matrix A:\n",A)

inv_A = np.linalg.inv(A) #inverse function
print("\nInverse Matrix A:\n",inv_A) #prints inverse matrix of A

B = np.array([[0],[0]]) #matrix B
print("\nMatrix B:\n",B)

X = np.dot(inv_A,B) #dot product of the inverse matrix A and matrix B
print("\nDot Product:\n",X)

Matrix A:
 [[-12   3]
 [  4   1]]

Inverse Matrix A:
 [[-0.04166667  0.125     ]
 [ 0.16666667  0.5       ]]

Matrix B:
 [[0]
 [0]]

Dot Product:
 [[0.]
 [0.]]


In [35]:
#Example 1

A = np.array([[-6,3],[4,5]]) #matrix A
print("Matrix A:\n",A)

w,v = np.linalg.eig(A) #eig method to find the eigenvalue and eigenvector of matrix A
print("\nThe eigenvalue/s is/are:",w) #prints eigenvalues of w
print("\nThe eigenvector/s is/are:\n",v) #prints eigenvectors of v

#x = v.round() #prints rounded values of eigenvectors
#print(x)

Matrix A:
 [[-6  3]
 [ 4  5]]

The eigenvalue/s is/are: [-7.  6.]

The eigenvector/s is/are:
 [[-0.9486833  -0.24253563]
 [ 0.31622777 -0.9701425 ]]


In [36]:
#Example 2

A = np.array([[2, 2, 4],[1, 3, 5],[2, 3, 4]]) #matrix A
print("Matrix A:\n",A)
s,t = np.linalg.eig(A) #eig method to find the eigenvalue and eigenvector of matrix A
print("\nThe eigenvalue/s is/are:",s.round()) #prints eigenvalues of s
print("\nThe right eigenvector/s is/are:",t.round()) #prints eigenvalues of t

C = np.dot(A,t.round()) #dot product of matrix A and eigenvector
print("\nDot product:\n",C)

Matrix A:
 [[2 2 4]
 [1 3 5]
 [2 3 4]]

The eigenvalue/s is/are: [ 9.  1. -1.]

The right eigenvector/s is/are: [[-1. -1. -0.]
 [-1.  1. -1.]
 [-1. -0.  1.]]

Dot product:
 [[-8.  0.  2.]
 [-9.  2.  2.]
 [-9.  1.  1.]]
