<a href="https://colab.research.google.com/github/Mtigno14/Linear-Algebra-58019/blob/main/Final_Exam.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Final Exam

###Problem 1.

In [42]:
#manual equation
#A + B + C = 89
#A + 4C = 89
#5C = 95

left = np.array([[1,1,1],[1,0,4],[0,0,5]])    #the two matrix are based off in equations above
right = np.array([[89],[89],[95]])
each_amount = np.linalg.inv(left).dot(right)  #gets the inverse of the first matrix and then multiply the second matrix
print("The cash each student have in their banks:\n",each_amount) #prints the cash each student have in total of 89

The cash each student have in their banks:
 [[13.]
 [57.]
 [19.]]


###Problem 2.

In [43]:
import numpy as np

A = np.array([[3,-1,1],[9,-3,3],[-12,4,-4]]) #matrix A (left side of the equation)
print(A)

B = np.array([[5],[15],[-20]]) #matrix B (right side of the equation)
print("\n",B)

inv_A = np.linalg.pinv(A) #it seems to have an error saying it is a singular matrix. (means theres nothing to inverse with)
print("\n",inv_A)         #thus i tried the psuedo inverse for the matrix in order to determine it.
                          #the psuedo inverse in simple terms generalized the matrix that cannot be invertible.

X = np.linalg.pinv(A).dot(B)
print("\n",X)

X = np.dot(inv_A,B) #simply the dot product of matrix A and matrix B
print("\n",X)

[[  3  -1   1]
 [  9  -3   3]
 [-12   4  -4]]

 [[  5]
 [ 15]
 [-20]]

 [[ 0.01048951  0.03146853 -0.04195804]
 [-0.0034965  -0.01048951  0.01398601]
 [ 0.0034965   0.01048951 -0.01398601]]

 [[ 1.36363636]
 [-0.45454545]
 [ 0.45454545]]

 [[ 1.36363636]
 [-0.45454545]
 [ 0.45454545]]


###Problem 3.

In [13]:
import numpy as np
from scipy.linalg import solve

A = np.array([[8,5,-6],[-12,-9,12],[-3,-3,5]]) #matrix A
print("Matrix A:\n",A)

x,y = np.linalg.eig(A) #eig method to find the eigenvalue and eigenvector of matrix A
print("\nThe eigenvalue/s is/are:",x) #prints eigenvalues of x
print("\nThe eigenvectors are:\n",y) #prints eigenvectors of y
print("\nThe eigenvectors are:\n",y.round()) #rounded eigenvectors

Matrix A:
 [[  8   5  -6]
 [-12  -9  12]
 [ -3  -3   5]]

The eigenvalue/s is/are: [-1.  3.  2.]

The eigenvectors are:
 [[ 3.01511345e-01 -7.07106781e-01  7.07106781e-01]
 [-9.04534034e-01  7.07106781e-01  1.53837015e-15]
 [-3.01511345e-01 -2.26120075e-15  7.07106781e-01]]

The eigenvectors are:
 [[ 0. -1.  1.]
 [-1.  1.  0.]
 [-0. -0.  1.]]
