<a href="https://colab.research.google.com/github/Mtigno14/Linear-Algebra-58019/blob/main/Matrix_Algebra.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Python program to inverse

In [21]:
import numpy as np
A = np.array([[1,2],[4,7]])
B = np.linalg.inv(A)
print(B)

C = np.dot(A,B)
print(C)

[[-7.  2.]
 [ 4. -1.]]
[[1. 0.]
 [0. 1.]]


In [30]:
##Python Program to inverse a 3x3 Matrix

A = np.array([[6,1,1],[4,-2,5],[2,8,7]]) #original components
print(A)
B = np.linalg.inv(A)
print("\nThe inverse above is: ")
print(B)
C = np.transpose(A)
print("\ntransposed as: ")
print(C)

[[ 6  1  1]
 [ 4 -2  5]
 [ 2  8  7]]

The inverse above is: 
[[ 0.17647059 -0.00326797 -0.02287582]
 [ 0.05882353 -0.13071895  0.08496732]
 [-0.11764706  0.1503268   0.05228758]]

transposed as: 
[[ 6  4  2]
 [ 1 -2  8]
 [ 1  5  7]]


## Program Code Product of A and B

In [39]:
D = np.cross(A, B)
print(D)

[[-0.01960784  0.31372549 -0.19607843]
 [ 0.48366013 -0.04575163 -0.40522876]
 [-0.63398693 -0.92810458  1.24183007]]


#Coding Activity 3

In [42]:
#Create a Python Program to inverse and transpose a 4x4 matrix, A = ( [6,1,1,3],[4,-2,5,1],[2,8,7,6],[3,1,9,7] )

A = ([[6,1,1,3],[4,-2,5,1],[2,8,7,6],[3,1,9,7]])
print("\nThe original components")
print(A)
B = np.linalg.inv(A)
print("\nThe inverse is: ")
print(B)
C = np.transpose(A)
print("\nThe transpose is: ")
print(C)


The original components
[[6, 1, 1, 3], [4, -2, 5, 1], [2, 8, 7, 6], [3, 1, 9, 7]]

The inverse is: 
[[ 0.13368984  0.10695187  0.02139037 -0.09090909]
 [-0.00229183  0.02673797  0.14820474 -0.12987013]
 [-0.12987013  0.18181818  0.06493506 -0.02597403]
 [ 0.11000764 -0.28342246 -0.11382735  0.23376623]]

The transpose is: 
[[ 6  4  2  3]
 [ 1 -2  8  1]
 [ 1  5  7  9]
 [ 3  1  6  7]]
