<a href="https://colab.research.google.com/github/Mtigno14/Linear-Algebra-58019/blob/main/Midterm_Exam.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Question 1. Create a Python code that displays a square matrix whose length is 5 (10 points)

In [4]:
import numpy as np
A = np.zeros((5,5)) #this prints a 5x5 matrix
print(A)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


##Question 2. Create a Python code that displays a square matrix whose elements below the principal diagonal are zero (10 points)

In [5]:
import numpy as np

A = np.array([[2,4,6],[0,10,12],[0,0,18]]) #I simplified the matrix by making the elements print out an upper triangular matrix
print(A)

[[ 2  4  6]
 [ 0 10 12]
 [ 0  0 18]]


##Question 3. Create a Python code that displays a square matrix which is symmetrical (10 points)

In [6]:
import numpy as np
A = np.full((3,3),14) #this prints a matrix full of the same elements
print(A)

[[14 14 14]
 [14 14 14]
 [14 14 14]]


##Question 4. What is the inverse of matrix C? Show your solution by python coding. (20 points)

In [7]:
import numpy as np
A = np.array([[1,2,3],[2,3,3],[3,4,-2]]) #given matrix C of question 4
print(A)


[[ 1  2  3]
 [ 2  3  3]
 [ 3  4 -2]]


In [8]:
inv_A = np.linalg.inv(A) #this function will print out the inverse of the given stated matrix above
print(inv_A)

[[-3.6  3.2 -0.6]
 [ 2.6 -2.2  0.6]
 [-0.2  0.4 -0.2]]


##Question 5. What is the determinant of the given matrix in Question 4? Show your solution by python coding. (20 points)

In [9]:
import numpy as np
A = np.array([[1,2,3],[2,3,3],[3,4,-2]])
print(A)
print(round(np.linalg.det(A))) #this print function lets me solve the determinant of the matrix

[[ 1  2  3]
 [ 2  3  3]
 [ 3  4 -2]]
5


##Question 6. Find the roots of the linear equations by showing its python codes (30 points)

In [10]:
import numpy as np
A = np.array([[5,4,1],[10,9,4],[10,13,15]]) #creation of matrix from the linear equation
print(A)

inv_A=np.linalg.inv(A)  #a function method to find the inverse of the matrix
print(inv_A)

[[ 5  4  1]
 [10  9  4]
 [10 13 15]]
[[ 5.53333333 -3.13333333  0.46666667]
 [-7.33333333  4.33333333 -0.66666667]
 [ 2.66666667 -1.66666667  0.33333333]]


In [11]:
B = np.array([[3.4],[8.8],[19.2]]) #these are the constants of each equation
print(B)

[[ 3.4]
 [ 8.8]
 [19.2]]


In [12]:
X = np.linalg.inv(A).dot(B) #this simply prints out the roots of the matrix
print(X)

[[0.2]
 [0.4]
 [0.8]]


In [13]:
X = np.dot(inv_A,B)
print(X)

[[0.2]
 [0.4]
 [0.8]]
