<a href="https://colab.research.google.com/github/Mtigno14/Linear-Algebra-58019/blob/main/Prelim_Exam.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Prelim Exam

##Question 1

In [25]:
import numpy as np

C = np.eye(4) #this is variable C that has the eye function where all elements are 0, except for the diagonal values
print("Answer: \n")
print(C) #the 4x4 matrix output

Answer: 

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


##Question 2

In [24]:
import numpy as np

C = np.eye(4) #this is variable C that has the eye function where all elements are 0, except for the diagonal values
D = C * 2 #this doubles the values of each elements
print("Answer: \n")
print("The original values: \n",C) #printing the original results
print("\n The doubled values: \n",D) #the doubled printing results

Answer: 

The original values: 
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

 The doubled values: 
 [[2. 0. 0. 0.]
 [0. 2. 0. 0.]
 [0. 0. 2. 0.]
 [0. 0. 0. 2.]]


##Question 3

In [23]:
import numpy as np

A = ([2,7,4]) #this is variable A
B = ([3,9,8]) #this is variable B

output = np.cross(A,B) #the cross product of a vector
print("Answer: \n ")
print(output) #result/output

Answer: 
 
[20 -4 -3]
