<a href="https://colab.research.google.com/github/Mtigno14/Linear-Algebra-58019/blob/main/Coding_Activity_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Create a NumPy program that solves for the unknown variables of linear systems:

##4x +10y+8z = 44
##10x+26y+26z = 128
##8x+26y+61z = 214

In [1]:
import numpy as np
A = np.array([[4,10,8],[10,26,26],[8,26,61]])
print(A)
inv_A = np.linalg.inv(A)
print(inv_A)

[[ 4 10  8]
 [10 26 26]
 [ 8 26 61]]
[[ 25.27777778 -11.16666667   1.44444444]
 [-11.16666667   5.          -0.66666667]
 [  1.44444444  -0.66666667   0.11111111]]


In [2]:
B = np.array([[44],[128],[214]])
print(B)

[[ 44]
 [128]
 [214]]


In [3]:
X = np.linalg.inv(A).dot(B)
print(X)

[[-8.]
 [ 6.]
 [ 2.]]


In [4]:
X = np.dot(inv_A,B)
print(X)

[[-8.]
 [ 6.]
 [ 2.]]
