<a href="https://colab.research.google.com/github/Mtigno14/Linear-Algebra-58019/blob/main/Python_Exercise_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Matrix and Its Operations

In [8]:
import numpy as np
A = np.array (([-5,0],[4,1]))
B = np.array (([6,-3],[2,3]))

In [7]:
sum = A + B
print(sum)

[[ 1 -3]
 [ 6  4]]


In [9]:
difference1 = B - A
print (difference1)

[[11 -3]
 [-2  2]]


In [10]:
difference2 = A - B
print (difference2)

[[-11   3]
 [  2  -2]]
