<a href="https://colab.research.google.com/github/Mtigno14/Linear-Algebra-58019/blob/main/Python_Exercise_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Representing Vectors

In [6]:
import numpy as np
A = np.array([4,3])
B = np.array([2,-5])

print('Vector A is',A)
print('Vector B is',B)

Vector A is [4 3]
Vector B is [ 2 -5]


##Describing Vectors in NumPy

In [14]:
import numpy as np
ball1 = np.array([1,2,3])
ball2 = np.array([0,1,-1])
pool = np.array([ball1,ball2])

pool.ndim #for dimensions
pool.shape #for shapes

(2, 3)

In [23]:
X = np.array([[2,4,6],[1,3,5]])
X
pool.ndim
X.ndim
X.size

6

#Space

###Vector spaces are mathematical objects that abstractly capture the geometry and algebra of linear equations

In [27]:
VectorDef = "Vector spaces are mathematical objects that abstractly capture the geometry and algebra of linear equations."
print(VectorDef)

Vector spaces are mathematical objects that abstractly capture the geometry and algebra of linear equations.


####Addition of Vectors

In [28]:
addend1 = np.array([2,4,6])
addend2 = np.array([1,3,5])
sum = addend1 + addend2
print(sum)

[ 3  7 11]


In [29]:
addend1 = np.array([2,4,6])
addend2 = np.array([1,3,5])
resultant = addend1 + addend2
print(resultant)

[ 3  7 11]


####Subtraction of Vectors

In [30]:
difference = addend1-addend2
print(difference)

[1 1 1]


In [31]:
difference2 = np.subtract(addend1, addend2)
print(difference2)

[1 1 1]


####Scaling

In [34]:
A = np.array([1,5,8,9])
S = 5*A
print(S)

[ 5 25 40 45]


####Cross Product

In [36]:
import numpy as np

A = np.array([2,3])
B = np.array([1,7])

output = np.cross(A,B)
print(output)

11


In [37]:
import numpy as np

A = np.array([2,3])
B = np.array([1,7])

cross = np.cross(A,B)
print(cross)

11


In [38]:
import numpy as np
A = np.array([2,3])
B = np.array([1,7])

dot = np.dot(A,B)
print(dot)

23
