<a href="https://colab.research.google.com/github/Mtigno14/Linear-Algebra-58019/blob/main/Vectors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Matrix Algebra


In [ ]:
import numpy as np
a = np.array([1,2,3,])
print(a)

[1 2 3]


In [ ]:
import numpy as np
b = np.array(([1,2,3,],[4,5,6]))
print(b)

[[1 2 3]
 [4 5 6]]


In [ ]:
import numpy as np
c = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(c)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
import numpy as np
d = np.full ((3,3),7)
print(d)

[[7 7 7]
 [7 7 7]
 [7 7 7]]


In [ ]:
import numpy as np
a = np.array ([[1,2,3],[4,5,6],[7,8,9]])
print(a)

a = np.diagonal ([[1,2,3],[4,5,6],[7,8,9]])
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 5 9]


In [ ]:
import numpy as np
f = np.eye(3)
print(f)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
import numpy as np
z = np.zeros((3,3))
print(z)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
import numpy as np
b = np.empty((0,12))
print(b)

[]


#Operations

In [ ]:
import numpy as np
x = np.full ((3,3),7)
print(x+x)

[[14 14 14]
 [14 14 14]
 [14 14 14]]


In [ ]:
import numpy as np
x = np.full ((3,3),7)
print(x-x)

[[0 0 0]
 [0 0 0]
 [0 0 0]]
